# Generated by Django 2.1.5 on 2019-02-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='secondhead',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
